### ISSUE TITLE
pytest tests are broken for me

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/spras#114]
Hi All (& tagging @ctrlaltaf) - I'm trying to run the tests using `pytest -s` from the `spras/` directory. However, I'm getting an error that I _think_ might be related to `matplotlib` because of this line:

```
OSError: The baseline image directory does not exist. This is most likely because the test data is not installed. You may need to install matplotlib from source to get the test data.
```

The full output is below. Did anyone else have this issue? The tests pass in GitHub Actions, so I'm assuming this is an issue on my end (it might be something silly). Thanks! 

```
(spras) aritz@C02D34WXML85 spras % pytest -s       
============================= test session starts ==============================
platform darwin -- Python 3.8.16, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/aritz/Documents/github/spras
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
../../../opt/miniconda3/envs/spras/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:843: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
env/lib/python3.8/site-packages/matplotlib/tests/__init__.py:6: in <module>
    raise IOError(
E   OSError: The baseline image directory does not exist. This is most likely because the test data is not installed. You may need to install matplotlib from source to get the test data.
=========================== short test summary info ============================
ERROR  - OSError: The baseline image directory does not exist. This is most l...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.93s ===============================

```

**Comment by agitter** [comment]
I confirmed I can run pytest locally on the master branch. The error message suggests that pytest is trying to run the matplotlib tests instead of the spras tests. I'm not sure how that could happen.

**Comment by annaritz** [comment]
Okay, will take a closer look on Friday.

Anna

**Comment by ctrlaltaf** [comment]
I had an issue where I tried `pytest test/LocalNeighborhood/test_ln.py` on the `spras/` directory, when I wanted to locally run the tests and received the following message

`============================================================================================ ERRORS =============================================================================================
______________________________________________________________________ ERROR collecting test/LocalNeighborhood/test_ln.py _______________________________________________________________________
ImportError while importing test module '/Users/abarelvi/spras/test/LocalNeighborhood/test_ln.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../anaconda3/envs/spras/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/LocalNeighborhood/test_ln.py:8: in <module>
    from src.local_neighborhood import LocalNeighborhood
E   ModuleNotFoundError: No module named 'src'
==================================================================================== short test summary info ====================================================================================
ERROR test/LocalNeighborhood/test_ln.py
`
I also have the same issue when I use `pytest -s test/LocalNeighborhood/test_ln.py `

Instead, I used `python -m pytest test/LocalNeighborhood/test_ln.py` which solved the issue for me

**Comment by annaritz** [comment]
Yep that did it! Thanks @ctrlaltaf
