### ISSUE TITLE
All Pairs Shortest Paths Output

### ISSUE THREAD

**Issue by ntalluri** [Reed-CompBio/spras#125]
Even though the function for parsing APSP outputs writes a tab-separated csv, the text file doesn't have a tab separating the two nodes, but everything else does. 

`def parse_output(raw_pathway_file, standardized_pathway_file):
        """
        Convert a predicted pathway into the universal format
        @param raw_pathway_file: pathway file produced by an algorithm's run function
        @param standardized_pathway_file: the same pathway written in the universal format
        """
        df = pd.read_csv(raw_pathway_file, sep='\t', header=None)
        df['Rank'] = 1  # add a rank column of 1s since the edges are not ranked.
        df = readd_direction_col_undirected(df)
        df.to_csv(standardized_pathway_file, header=False, index=False, sep='\t')
`

* This is probably an easy fix, but I wrote it down so I don't forget.

**Comment by agitter** [comment]
I thought we modified it to output tab-separated output files. Could you possibly have a stale version of the Docker image locally? Does it work if you rebuild the latest Dockerfile?

**Comment by ntalluri** [comment]
I just updated my image, that was exactly what it was
