### ISSUE TITLE
Unable to run some PRMs in isolation

### ISSUE THREAD

**Issue by jhiemstrawisc** [Reed-CompBio/spras#131]
I was just working on overhauling some configuration mechanisms, and as a part of the process I was going through and running each PRM in isolation (both to cut down on overall runtime and to make sure that particular PRM was functioning as expected).

For some of the methods, like allpairs and meo, snakemake threw a cryptic fatal error related to the ml module (ignore exact line numbers):
```
Running docker containers
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...
components=2 is not valid. Setting components to 1.
/opt/conda/envs/spras/lib/python3.8/site-packages/sklearn/decomposition/_pca.py:525: RuntimeWarning: invalid value encountered in divide
  explained_variance_ = (S**2) / (n_samples - 1)
[Thu Sep 21 20:48:17 2023]
Error in rule ml_analysis:
    jobid: 0
    input: output/data0-meo-params-GKEDDFZ/pathway.txt
    output: output/data0-pca.png, output/data0-pca-variance.txt, output/data0-pca-coordinates.txt, output/data0-hac-vertical.png, output/data0-hac-clusters-vertical.txt, output/data0-hac-horizontal.png, output/data0-hac-clusters-horizontal.txt, output/data0-ensemble-pathway.txt

RuleException:
IndexError in file /workspaces/spras/spras.justin.repo/Snakefile, line 278:
index 1 is out of bounds for axis 1 with size 1
  File "/workspaces/spras/spras.justin.repo/Snakefile", line 278, in __rule_ml_analysis
  File "/workspaces/spras/spras.justin.repo/src/analysis/ml.py", line 127, in pca
  File "/opt/conda/envs/spras/lib/python3.8/concurrent/futures/thread.py", line 57, in run
```

After some debugging, I found that the offending input was from the Snakefile's `pca_params` dict. My hunch was that `n_samples` was tied to the number of PRMs run in the workflow, and that to prevent division by 0, I needed at least two algorithms for comparison. Running pathlinker in addition to meo solved the issue.

My question is whether this is actually a bug, or if we truly never expect SPRAS to be run against single PRMs? If the former, I think this is a quick fix because the variance of a single observation is 0.

**Comment by agitter** [comment]
This is related to #117 but looks like slightly different behavior. We do intend to allow SPRAS to run with single PRMs and single parameter configurations, so this is a bug. I assume the PRMs that succeeded are those that run with multiple parameter combinations and those that failed had a single parameter combination in the config file.

@ntalluri we may want to prioritize making PCA and ML analyses more robust to address this and #117 after directed edge support is merged.

**Comment by ntalluri** [comment]
@jhiemstrawisc  I know this pretty late, but do you remember how you configured your config file to create this error?
