### ISSUE TITLE
Decouple Ensemble Step from ML Step

### ISSUE THREAD

**Issue by ntalluri** [Reed-CompBio/spras#163]
With the updates to the code in https://github.com/Reed-CompBio/spras/pull/160, algorithms with multiple parameter combinations will now run aggregate per-algorithm ML code. As a result, we won't be able to run ensemble code for algorithms with one or fewer parameter combinations. To ensure we have ensemble networks for all algorithms, we need to create a new rule that uses the ensembling code per algorithm, rather than running all the ML code for each algorithm.

**Comment by agitter** [comment]
Closed by #175
