### ISSUE TITLE
Check robustness of PCA representation

### ISSUE THREAD

**Issue by agitter** [Reed-CompBio/spras#181]
Based on a discussion with @brycejoh16 we realized we should confirm that our PCA representation of a collection of graphs is robust to the order in which the graphs and the edges are presented. We can try randomly permuting the rows and columns of the graph X edge matrix before running PCA and confirm the outputs still pass our test cases.

**Comment by ntalluri** [comment]
I checked the robustness of PCA. Shuffling the columns (the algorithms) and the rows (the edges) do not change the output of PCA.

**Comment by ntalluri** [comment]
https://github.com/Reed-CompBio/spras/pull/185

added pca robustness test to test_ml

**Comment by agitter** [comment]
Closed by #185
