### ISSUE TITLE
Specifying input and output formats

### ISSUE THREAD

**Issue by agitter** [Reed-CompBio/spras#4]
We can finalize the universal input and output formats that we have previously discussed.  Once these are locked in, we can document them in the main readme.

Input file formats:
- How to list interactions
- How to optionally denote edge directionality (or other edge features?)
- How to provide node annotations

Output file format:
- How to list interactions and specify directionality (required?)
- How to provide node annotations (is this needed?)

**Comment by annaritz** [comment]
Picking up on this issue related to **input file formats.** @prameshsingh has added some in the `example/` directory in the `input-data` branch. We propose:

1. Adding a README to this directory (suggested by @agitter)
2. Having **two** file types: one that denotes a graph (a two-column edgelist, with optional additional cols), and one that denotes a node list (a one-column list of node names, with optional additional cols).  For example, if we are given `EGFR1-sources.txt` and `EGFR1-targets.txt` node lists for EGFR, then `EGFR1-nodes.txt` will be generated from these files for PathLinker in `prepareInputs()`. 
3. Write code in PathLinker's `prepareInputs()` to actually generate this file. 

For now, we're leaving the large interactome and the `*-edges.txt` files as-is.

**Comment by agitter** [comment]
At our recent meeting, we decided to add a header row to the SPRAS pathway output file format. This will disambiguate the third column of numeric scores, which is currently a rank for individual pathways but can also be an edge frequency in an ensemble pathway.

**Comment by agitter** [comment]
Closed by https://github.com/Reed-CompBio/spras/pull/142, which added a markdown file documenting the output file format.
