### ISSUE TITLE
candidate files to remove

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/spras#6]
It seems like `run.py` and `draft-interface.py` were the first attempts to make a command line interface before we switched to Snakemake. Should these be removed from `main`?

**Comment by agitter** [comment]
I agree that we're not using any of this code and are unlikely to use it directly.  It could still serve as a useful reference for a future front end way to interact with the pipeline.  Even with the Snakemake workflow, we may want to have a user-friendly wrapper that configures and launches the workflow.

Should we move these to `src/prototype`, `src/mockup`, or something similar?

**Comment by annaritz** [comment]
Making a subdirectory within `src/` is a good idea. We can resolve this issue when we resolve Issue #7.
