### ISSUE TITLE
Omics Integrator 1 "No space left" error is back

### ISSUE THREAD

**Issue by sverchkov** [Reed-CompBio/spras#60]
Running Omics Integrator 1 on Singularity with a large network I'm getting the error:

```
Traceback (most recent call last):
  File "/OmicsIntegrator/scripts/forest.py", line 1464, in <module>
    main()
  File "/OmicsIntegrator/scripts/forest.py", line 1424, in main
    (edgeList, info) = inputObj.runPCSF(options.msgpath, options.seed)
  File "/OmicsIntegrator/scripts/forest.py", line 576, in runPCSF
    1-float(self.undirEdges[edgeNode1][edgeNode2])))
IOError: [Errno 28] No space left on device
```

This is in the same environment as the last time we saw this issue https://github.com/Reed-CompBio/spras/issues/37#issuecomment-892714685 but I'm not certain if it's the exact same problem (I don't yet have a full grasp over which volume is mapped where).

PS. this error is printed out but what actually halts the pipeline is failure to rename the consequently non-existent output file, maybe the reconstruct rule should explicitly fail if OI1 has a nonzero return code?

**Comment by agitter** [comment]
Thanks for the report.  Based on [where the error occurs](https://github.com/fraenkel-lab/OmicsIntegrator/blob/0a57ede6beeef6e63b86d19898e560d62015e85d/scripts/forest.py#L575-L576), it seems that the Singularity working directory can't support making this copy of the input network.  How large is the input network you're using?

> maybe the reconstruct rule should explicitly fail if OI1 has a nonzero return code

Yes, I agree with this.  I'll need to look more closely at what type of errors we can throw based on the information we get back from the Singularity and Docker calls.

**Comment by sverchkov** [comment]
The network has 1053138 edges, it's a 48MB file.
