### ISSUE TITLE
Example command dies on PathLinker run

### ISSUE THREAD

**Issue by annaritz** [Reed-CompBio/spras#64]
This must be an issue with me, not the code...we can talk about it tomorrow but wanted to share it here.

I'm trying to use SPRAS to generate some PathLinker & OI2 results, and realized that running the example command (`snakemake --cores 1 --configfile config/config.yaml`) gives me the same issue.  OI2 works fine, but PathLinker does not execute. Here is the PathLinker command called:

```
Running PathLinker with arguments: python /PathLinker/run.py /spras/BB5IA2J/network.txt /spras/KQIKRVB/nodetypes.txt --output /spras/ISGJBJY/data0-pathlinker-params-6SWY7JS/out -k 200
```

The error is that `/PathLinker/run.py` cannot be found in the `reedcompbio/pathlinker` Docker image. This seems very odd (especially since OmicsIntegrator runs fine within its image).

The full error is here:

Command '['python', '/PathLinker/run.py', '/spras/BB5IA2J/network.txt', '/spras/KQIKRVB/nodetypes.txt', '--output', '/spras/ISGJBJY/data0-pathlinker-params-6SWY7JS/out', '-k', '200']' in image 'reedcompbio/pathlinker' returned non-zero exit status 2: b"python: can't open file '/PathLinker/run.py': [Errno 2] No such file or directory\nERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '/PathLinker/run.py', '/spras/BB5IA2J/network.txt', '/spras/KQIKRVB/nodetypes.txt', '--output', '/spras/ISGJBJY/data0-pathlinker-params-6SWY7JS/out', '-k', '200']' command failed.  (See above for error)\n"

The `pytests` for PathLinker are failing for the same Termination error. Any help is apprecited - Thanks!

**Comment by agitter** [comment]
I double checked that the tests pass locally for me using the version at commit 54993079af3b2f7f8fba1968a42fb08031f6f1e5.

I wonder if this could be related to the updates to how the PathLinker image is used.  If you have an older version of the Docker image and the SPRAS code now expects a newer version, that incompatibility may cause this error.  Having proper versions (#56) would be helpful for debugging this.

If you run `docker pull reedcompbio/pathlinker` and then test SPRAS again does anything change?
