### ISSUE TITLE
MinCostFlow algorithm takes only one input at a time

### ISSUE THREAD

**Issue by ntalluri** [Reed-CompBio/spras#81]
Currently, the mincostflow algorithm in spras does not support multiple flows and capacities. Since it only works for one flow and one capacity sent through the flow, this needs to be updated so that multiple variants may be sent through at the same time.

**Comment by agitter** [comment]
While testing this, we noticed that if we run with 0 flow we get an EmptyDataError from the `read_csv` call in `parse_output`. We could catch that and write an empty file.

The issue may be with the parameter values provided, not the multiple values. I tested with `flow: [1, 0]` and the config file was parsed correctly.
