### ISSUE TITLE
Dealing with Protein Names that Are A Combination of Multiple Names

### ISSUE THREAD

**Issue by ntalluri** [Reed-CompBio/spras#82]
There isn't a good method to get the names of nodes with multiple names since there isn't anything in the output files that indicates which names go to which node. It would be easier if the output files had a delimiter (such as |) between each node and weight.

**Comment by agitter** [comment]
Can you please add an example of a problematic output?

**Comment by ntalluri** [comment]
input: this node is spaced 1

output:
,test-spaced
node|||this,1

**Comment by agitter** [comment]
Will that be addressed by #79? Once we switch to tab-separated pathway outputs, nodes will be allowed to contain spaces in their name. So the input would have to be
`this	node is spaced	1`
or
`this node is	spaced	1`
etc.

This looks similar to the example covered by the new `test/ml/input/spaces/spaces.txt` test case.

**Comment by agitter** [comment]
We agreed this was closed by #79
